export {
  ContextplaneApiError,
  clientFromRequest,
  createContextplaneClient,
  type ContextplaneClient,
  type ContextplaneClientOptions,
  type ContextplaneErrorItem,
  type ContextplaneRequestOptions,
  type ContextplaneResponse,
} from "./client";
export {
  addVocabularyValue,
  changeAutopromotePredicate,
  createProgressionOverride,
  getAutopromoteAllowlist,
  getConformancePolicy,
  getPromotionPolicy,
  graphVocabularyKinds,
  listEdgePropertySchemas,
  listExternalSystems,
  listEntityTypeSchemas,
  listExtractionStrategies,
  listMemoryCalibration,
  listMemorySources,
  deletePiiFieldPolicy,
  listPiiFieldPolicies,
  listPiiPatterns,
  listProgressionDefinitions,
  listProgressionOverrides,
  listSyncRuns,
  listSyncSources,
  listVocabularyValues,
  purgeActorPersonalData,
  refitMemoryCalibration,
  replacePromotionPolicy,
  resetMemorySourceBreaker,
  setEntityTypeSchemaAdvisory,
  setPiiFieldPolicy,
  setPiiPatternEnabled,
  setSyncSourceActive,
  setVocabularyDeprecated,
  triggerSync,
  updateExtractionStrategy,
  type AdminAllowlist,
  type CalibrationMapping,
  type CalibrationRefitInput,
  type CalibrationRefitReceipt,
  type ConformancePolicy,
  type EdgePropertySchema,
  type EntityTypeSchema,
  type ExternalSystem,
  type GraphVocabularyKind,
  type ListProgressionOverridesParameters,
  type ListSyncRunsParameters,
  type PiiFieldPolicy,
  type PiiFieldType,
  type PiiPolicy,
  type PiiPattern,
  type ProgressionDefinition,
  type ProgressionOverride,
  type ProgressionOverrideInput,
  type PromotionPolicy,
  type PromotionPolicyInput,
  type PurgeReceipt,
  type SourcePolicy,
  type Strategy,
  type StrategyUpdate,
  type SyncRun,
  type SyncSource,
  type TriggerSyncReceipt,
  type VocabularyValue,
} from "./admin";
export {
  activateAgentInstruction,
  getAgentAccuracy,
  getAgentAutonomy,
  getAgentFailurePatterns,
  listAgentInstructions,
  proposeAgentInstruction,
  rollbackAgentInstruction,
  type AccuracyGroup,
  type AgentAccuracy,
  type AgentAutonomy,
  type AgentInstruction,
  type AgentWindowParameters,
  type FailureExample,
  type FailureGroup,
  type FailurePatternReport,
  type ProposeInstructionInput,
} from "./agents";
export {
  applyQuarantine,
  previewQuarantine,
  revertQuarantine,
  type AppliedQuarantine,
  type QuarantinePreview,
  type QuarantineSelector,
} from "./quarantine";
export {
  queryAuditRecords,
  type AuditRecord,
  type AuditRecordPage,
  type AuditSnapshot,
  type QueryAuditRecordsParameters,
} from "./audit";
export {
  changeCapabilityLifecycle,
  catalogEntityTypes,
  createCatalogEntity,
  createCapabilityAdoption,
  createCapabilityArtifact,
  createCapabilitySubscription,
  deleteCapability,
  deleteCapabilityAdoption,
  deleteCapabilityArtifact,
  deleteCapabilitySubscription,
  getCapability,
  getCapabilityInterface,
  listCapabilities,
  listCapabilityAdoptions,
  listCapabilityArtifacts,
  listCapabilitySubscriptions,
  previewCapabilityVersion,
  putCapabilityInterface,
  setCapabilityVisibility,
  updateCapability,
  updateCapabilitySubscription,
  type AffectedConsumer,
  type CapabilityInterface,
  type CapabilityVersionPreview,
  type CatalogAdoption,
  type CatalogArtifact,
  type CatalogArtifactPage,
  type CatalogCapabilityDetail,
  type CatalogCapabilityRead,
  type CatalogCapabilityPage,
  type CatalogCapabilitySummary,
  type CatalogEntityType,
  type CatalogSubscription,
  type ChangeCapabilityLifecycleInput,
  type CreateCapabilityAdoptionInput,
  type CreateCapabilityArtifactInput,
  type CreateCapabilityInput,
  type CreateCatalogEntityInput,
  type CreateCapabilitySubscriptionInput,
  type ListCapabilitiesParameters,
  type PreviewCapabilityVersionInput,
  type PutCapabilityInterfaceInput,
  type SetCapabilityVisibilityInput,
  type UpdateCapabilityInput,
  type UpdateCapabilitySubscriptionInput,
} from "./catalog";
export {
  getTenantLearningAggregates,
  ingestTenantSignal,
  listTenantLearningMetrics,
  listTenantNotifications,
  markTenantNotificationRead,
  type SignalIngestInput,
  type SignalIngestReceipt,
  type StructuredServiceResult,
  type TenantNotification,
  type TenantNotificationPage,
} from "./activity";
export {
  addIntentParticipant,
  appendIntentCheckpoint,
  getIntentCheckpoint,
  getIntentCheckpointByDigest,
  listIntentParticipants,
  removeIntentParticipant,
  type AddParticipantInput,
  type AppendCheckpointInput,
  type IntentCheckpoint,
  type IntentParticipant,
} from "./intents";
export {
  assignTenantOwnership,
  findTargetOwners,
  getGoverningBinding,
  getProfileConformance,
  getTenantOwnershipAssignment,
  listPrincipalOwnership,
  planProfileBinding,
  publishProfileExtension,
  publishProfileRevision,
  transitionProfileBinding,
  transitionTenantOwnership,
  type AssignOwnershipInput,
  type GoverningBinding,
  type OwnershipAssignment,
  type OwnershipTransitionInput,
  type PlanProfileBindingInput,
  type ProfileBindingTransitionInput,
  type PublishProfileExtensionInput,
  type PublishProfileRevisionInput,
} from "./ownership";
export {
  PRECONDITION_FAILED,
  createRelationship,
  getRelationship,
  queryRelationships,
  relationshipQueryDirections,
  relationshipWriteIntents,
  updateRelationship,
  type GovernedRelationship,
  type GovernedRelationshipPage,
  type GovernedRelationshipRead,
  type RelationshipEndpoints,
  type RelationshipProfileAttribution,
  type RelationshipProvenanceInput,
  type RelationshipProvenanceSummary,
  type RelationshipQueryDirection,
  type RelationshipQueryInput,
  type RelationshipTargetRevision,
  type RelationshipTemporalInput,
  type RelationshipTemporalState,
  type RelationshipValidationOutcome,
  type RelationshipWriteIdentity,
  type RelationshipWriteInput,
  type RelationshipWriteIntent,
  type RelationshipWriteResult,
} from "./relationships";
export {
  IDENTITY_AMBIGUOUS,
  qualifiedHandle,
  resolveEntity,
  type EntityIdentity,
  type EntityResolution,
} from "./entityResolution";
export {
  assertEntity,
  entityWriteIntents,
  updateEntity,
  type EntityProvenanceInput,
  type EntityTargetRevision,
  type EntityWriteIdentity,
  type EntityWriteInput,
  type EntityWriteIntent,
  type EntityWriteResult,
} from "./entityWrites";
export {
  assertMemoryClaim,
  claimEvidenceKinds,
  claimVisibilities,
  contextBlockNames,
  contextBlockStates,
  contextEnvelopeStates,
  contextFeedbackRatings,
  createWorkspace,
  createWorkspaceEntry,
  deleteWorkspace,
  deleteWorkspaceEntry,
  getContextReceipt,
  getContextReceiptExclusions,
  getContextReceiptReferences,
  getCapabilityUsage,
  getDailyUsageSeries,
  getMemoryClaim,
  getMemoryClaimHistory,
  getMemoryCurationCounts,
  getPromotionProposal,
  getConsumerRelationshipProjection,
  getProviderRelationshipProjection,
  getRelationshipBlastRadius,
  getRelationshipDependencies,
  getRelationshipDependents,
  getToolUsage,
  getUsageSummary,
  getWhoAmI,
  getWorkspace,
  listClaimPredicates,
  listSessionEvents,
  listSessions,
  listMemoryClaims,
  listMemoryCurationQueue,
  listPromotionProposals,
  listWorkspaceEntries,
  listWorkspaces,
  promotionProposalStates,
  relationshipDepths,
  relationshipDirections,
  reviewPromotionProposal,
  recordContextFeedback,
  resolveContext,
  searchMemoryClaims,
  searchWorkspaceEntries,
  sessionEventKinds,
  memoryClaimPersonas,
  updateWorkspace,
  updateWorkspaceEntry,
  workspaceEntryKinds,
  workspaceOwnerKinds,
  type ContextBlock,
  type ContextBlockName,
  type ContextBlockState,
  type ContextEnvelope,
  type ContextEnvelopeState,
  type ContextExclusion,
  type ContextFeedback,
  type ContextFeedbackRating,
  type ContextItem,
  type ContextReceipt,
  type ContextReference,
  type ContextTrust,
  type AssertClaimInput,
  type CapabilityUsage,
  type CapabilityUsageRanking,
  type ClaimAssertionReceipt,
  type ClaimEvidenceItem,
  type ClaimEvidenceKind,
  type ClaimPredicate,
  type ClaimVisibility,
  type CreateWorkspaceEntryInput,
  type CreateWorkspaceInput,
  type DailyUsagePoint,
  type DailyUsageSeries,
  type GetRelationshipBlastRadiusParameters,
  type GetRelationshipDependenciesParameters,
  type GetRelationshipProjectionParameters,
  type GetRelationshipTraversalParameters,
  type ListSessionEventsParameters,
  type ListSessionsParameters,
  type ListMemoryClaimsParameters,
  type ListMemoryCurationParameters,
  type ListPromotionProposalsParameters,
  type ListWorkspaceEntriesParameters,
  type ListWorkspacesParameters,
  type PromotionProposal,
  type PromotionProposalDecision,
  type PromotionProposalPage,
  type PromotionProposalState,
  type RecordContextFeedbackInput,
  type ResolveContextInput,
  type ReviewPromotionProposalInput,
  type SessionEvent,
  type SessionEventKind,
  type SessionSummary,
  type MemoryCitation,
  type MemoryClaim,
  type MemoryClaimHistory,
  type MemoryClaimHistoryItem,
  type MemoryClaimPersona,
  type MemoryCurationCounts,
  type MemoryCurationItem,
  type MemoryCurationPage,
  type RelationshipDependencyResult,
  type RelationshipDepth,
  type RelationshipDirection,
  type RelationshipEdge,
  type RelationshipEntity,
  type RelationshipProjectionResult,
  type RelationshipTraversalResult,
  type SearchMemoryClaimsParameters,
  type SurfaceUsageSummary,
  type ToolUsage,
  type ToolUsageRanking,
  type UsageSummary,
  type UsageWindowParameters,
  type WhoAmI,
  type SearchWorkspaceEntriesParameters,
  type UpdateWorkspaceEntryInput,
  type UpdateWorkspaceInput,
  type Workspace,
  type WorkspaceEntry,
  type WorkspaceEntryKind,
  type WorkspaceEntryPage,
  type WorkspaceEntrySearchPage,
  type WorkspaceOwnerKind,
  type WorkspacePage,
  type WorkspaceWarning,
} from "./contextplane";
